app = "directus"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  KEY = "SET USING SECRETS"
  DB_CLIENT = "sqlite3"
  DB_FILENAME = "/litefs/directus.db"
  CACHE_ENABLED = false
  # CACHE_STORE = "redis"
  # CACHE_REDIS = "<redis url>"
  ADMIN_EMAIL = 'SET USING SECRETS'
  ADMIN_PASSWORD = 'SET USING SECRETS'
  # STORAGE_LOCATIONS = "s3"
  STORAGE_LOCAL_ROOT = "/data/directus/uploads"
  # STORAGE_R2_DRIVER = "s3"
  # STORAGE_R2_REGION = "auto"
  # STORAGE_R2_BUCKET = "<bucket name>"
  # STORAGE_R2_ENDPOINT = "<bucket endpoint>"
  # MESSENGER_STORE = "redis"
  # MESSENGER_NAMESPACE = "directus"
  # MESSENGER_REDIS_URL = "<redis url>"
  TELEMETRY = false
  # Make sure to set this in production
  # (see https://docs.directus.io/self-hosted/config-options#general)
  PUBLIC_URL = "https://<app name>.fly.dev"

[mounts]
  source="directus"
  destination="/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  enable_consul = true

[[services]]
  http_checks = []
  internal_port = 8056
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
